#EXTM3U
#EXTINF:-1 group-title="FRANCE" tvg-id="BFM TV" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/bfmtv.gif", BFM TV
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2019/17.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="FRANCE 24" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/france24.gif", FRANCE 24
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2007/17.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="i24 news" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/i24news.jpg", i24 news
https://opus.re/tkn/s0/ab2fe38e096bbe0a202bd7d7794e366eba5406ea/i24-news.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="itele" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/C-NEWS.jpg", itele
https://opus.re/tkn/s0/ab2fe38e096bbe0a202bd7d7794e366eba5406ea/cnews.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="TV5 info" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/tv5info.jpg", TV5 info
https://opus.re/france24/ab2fe38e096bbe0a202bd7d7794e366eba5406ea/v3plusinfo247hls_1_1.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="Euronews" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/euronews.jpg", Euronews
https://opus.re/euronews-fr/ab2fe38e096bbe0a202bd7d7794e366eba5406ea/live.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="crime-district" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/crime-district.jpg", crime-district
https://opus.re/allfrtvstrm/tkn/abwebtk/index.php/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/live.crimedistrict.tv/crimedistrict.isml/manifest.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="Discovery-investigation" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/discovery-investigation.png", Discovery-investigation
https://opus.re/allfrtvstrm/tkn/newcrab/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/index.m3u8?id=2934
#EXTINF:-1 group-title="FRANCE" tvg-id="Planete+ Crime-investigation" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/planete+ci.jpg", Planete+ Crime-investigation
https://opus.re/allfrtvstrm/tkn/tvone/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/f9cc32f4e5d665f59355da62d4bca4f7.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="Les enquetes impossibles" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/impossibles.jpg", Les enquetes impossibles
https://opus.re/allfrtvstrm/tkn/impossible/i/index.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="RDI" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/rdi.png", RDI
https://srclive-lh.akamaihd.net/i/canrdi_1@95877/master.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="RT NEWS" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/RT-FRANCE.PNG", RT NEWS
https://opus.re/srv/strm/rt.stream/ab2fe38e096bbe0a202bd7d7794e366eba5406ea/rt-fr/index2500.m3u8?1536505584
#EXTINF:-1 group-title="FRANCE" tvg-id="V" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/vtele-92x92.jpg", V
https://opus.re/allfrtvstrm/tkn/ca/veco/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/playlist.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="TVA" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/logo-tva.jpg", TVA
https://opus.re/allfrtvstrm/tkn/ca/tvaeco/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/playlist.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="RADIO-CANADA" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/src.png", RADIO-CANADA
https://opus.re/allfrtvstrm/tkn/ca/cbceco/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/chunklist.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="Canal Savoir" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/canal_savoir.jpg", Canal Savoir
https://opus.re/srv/strm/canal_savoir/ab2fe38e096bbe0a202bd7d7794e366eba5406ea/stream.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="CIVM" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/civm.jpg", CIVM
https://opus.re/allfrtvstrm/tkn/ca/srceco/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/chunklist.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="ARTE" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/Logo_Arte_noir.JPG", ARTE
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2029/17.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="TF1" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/tf1.jpg", TF1
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2027/17.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="France 2" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/chaine-france-2.png", France 2
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2004/17.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="France 3" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/chaine-france-3.png", France 3
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2008/17.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="France 4" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/chaine-france-4.png", France 4
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2009/17.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="France 5" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/chaine-france-5.png", France 5
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2010/17.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="France O" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/chaine-france-o.png", France O
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2015/17.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="M6" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/m6.gif", M6
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2026/17.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="6ter" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/6ter.png", 6ter
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2057/17.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="W9" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/w9.png", W9
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2022/17.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="D8" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/C8.jpg", D8
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2018/17.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="D 17" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/CStar.png", D 17
https://opus.re/allfrtvstrm/tkn/newcrab/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/index.m3u8?id=590
#EXTINF:-1 group-title="FRANCE" tvg-id="RMC Decouverte" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/rmc-d.jpg", RMC Decouverte
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2059/17.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="numero 23" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/23.png", numero 23
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2062/17.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="cherie 25" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/25.png", cherie 25
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2060/17.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="nrj 12" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/nrj12.png", nrj 12
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2017/17.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="TMC" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/tmc.gif", TMC
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2023/17.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="chaine-tfx" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/chaine-tfx.png", chaine-tfx
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2012/17.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="chaine-tf1-series-films" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/tf1-series-films-min.jpg", chaine-tf1-series-films
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2061/17.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="rts un" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/rtsun.jpg", rts un
https://opus.re/allfrtvstrm/tkn/rtsch/4BHusiCdEFfTUzNjUGyUnFsNTU4NCIsImVuAoUZNDY5IjoiCdEFfTUzNjU0ODCdEFf4NCIsImhhc2giOiI3NjCdEFf5CdEFfTBkCdEFf2NlAoUZNWFhYTIGyUnFsNjFmAoUZNGY2NmEyODA4CdEFfzAGyUnFsYSJ9/i/enc9uni_ch@191320/master.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="rts deux" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/rtsdeux.jpg", rts deux
https://opus.re/allfrtvstrm/tkn/rtsch/4BHusiCdEFfTUzNjUGyUnFsNTU4NCIsImVuAoUZNDY5IjoiCdEFfTUzNjU0ODCdEFf4NCIsImhhc2giOiI3NjCdEFf5CdEFfTBkCdEFf2NlAoUZNWFhYTIGyUnFsNjFmAoUZNGY2NmEyODA4CdEFfzAGyUnFsYSJ9/i/enc10uni_ch@191367/master.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="RTL9" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/rtl-9.png", RTL9
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2014/17.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="AB1" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/ab1.png", AB1
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2033/master.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="AB3" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/ab3.png", AB3
https://opus.re/allfrtvstrm/tkn/abwebtk/index.php/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/live.ab3.be/ab3.isml/manifest.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="TEVA" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/teva.png", TEVA
https://opus.re/allfrtvstrm/tkn/newcrab/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/index.m3u8?id=592
#EXTINF:-1 group-title="FRANCE" tvg-id="13eme rue" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/13emerue.png", 13eme rue
https://opus.re/allfrtvstrm/tkn/newcrab/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/index.m3u8?id=2929
#EXTINF:-1 group-title="FRANCE" tvg-id="Paris premiere" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/parispremiere.png", Paris premiere
https://opus.re/allfrtvstrm/tkn/newcrab/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/index.m3u8?id=589
#EXTINF:-1 group-title="FRANCE" tvg-id="tvbreizh" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/tvbreizh.png", tvbreizh
https://opus.re/allfrtvstrm/tkn/btv/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/tvbreizh.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="Rouge tv" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/rougetv.jpg", Rouge tv
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2047/17.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="TV5 Monde" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/tv5europe.jpg", TV5 Monde
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2006/17.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="SYFY" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/syfy.png", SYFY
https://opus.re/allfrtvstrm/tkn/sap2/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/index.m3u8?id=407
#EXTINF:-1 group-title="FRANCE" tvg-id="Zouzous" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/zouzou.jpg", Zouzous
https://opus.re/allfrtvstrm/tkn/france/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/ftviflivehdz-f.akamaihd.net/i/zouzous_live@88958/master.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="Boomerang" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/boomerang.JPG", Boomerang
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/6067/17.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="cartoon_network" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/Cartoon_Network_2010.png", cartoon_network
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2055/17.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="Gulli" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/gulli.jpg", Gulli
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2011/17.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="Game One" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/gameone.png", Game One
https://opus.re/allfrtvstrm/tkn/btv/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/gameone.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="BOING" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/BOING.JPG", BOING
https://opus.re/allfrtvstrm/tkn/wil/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/6049/17.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="Gong" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/gong.jpg", Gong
https://opus.re/tkn/s0/ab2fe38e096bbe0a202bd7d7794e366eba5406ea/gong-base.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="tiji" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/chaine-tiji.png", tiji
https://opus.re/allfrtvstrm/tkn/sap2/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/index.m3u8?id=404
#EXTINF:-1 group-title="FRANCE" tvg-id="MANGA" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/mangas.jpg", MANGA
https://opus.re/allfrtvstrm/tkn/abwebtk/index.php/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/live.mangas.fr/mangas.isml/manifest.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="nikelodeon 4 teen" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/nickelodeon.PNG", nikelodeon 4 teen
https://opus.cf/allfrtvstrm/tkn/bbb/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/nickelodeon_4teen/nickelodeon_4teen.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="nikelodeon junior" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/nickelodeon.PNG", nikelodeon junior
https://opus.cf/allfrtvstrm/tkn/bbb/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/nickelodeon_junior/nickelodeon_junior.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="nikelodeon" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/nickelodeon.PNG", nikelodeon
https://opus.cf/allfrtvstrm/tkn/bbb/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/nickelodeon/nickelodeon.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="Disney Channel" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/disney-channel.png", Disney Channel
https://opus.re/allfrtvstrm/tkn/btv/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/disney.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="Chasse et Pêche" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/chasseetpeche.png", Chasse et Pêche
https://opus.re/allfrtvstrm/tkn/abwebtk/index.php/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/live.chasseetpechetv.fr/chassepeche.isml/manifest.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="ABXPLORE" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/logo-ABX.png", ABXPLORE
https://opus.re/allfrtvstrm/tkn/abwebtk/index.php/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/live.abxplore.be/abxplore.isml/manifest.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="histoire" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/histoire.png", histoire
https://opus.re/allfrtvstrm/tkn/btv/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/histoire.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="Histoire" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/TLHTV.JPG", Histoire
https://opus.re/allfrtvstrm/tkn/abwebtk/index.php/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/live.toutelhistoire.com/toutelhistoire.isml/manifest.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="science & vie" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/S&V.PNG", science & vie
https://opus.re/allfrtvstrm/tkn/abwebtk/index.php/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/live.science-et-vie.tv/sciencevie.isml/manifest.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="Discovery science" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/discovery-science", Discovery science
https://opus.re/allfrtvstrm/tkn/newcrab/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/index.m3u8?id=2929
#EXTINF:-1 group-title="FRANCE" tvg-id="Discovery" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/discovery.jpg", Discovery
https://opus.re/allfrtvstrm/tkn/newcrab/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/index.m3u8?id=2928
#EXTINF:-1 group-title="FRANCE" tvg-id="animaux" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/animaux.png", animaux
https://opus.re/allfrtvstrm/tkn/abwebtk/index.php/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/live.animauxtv.fr/animauxtv.isml/manifest.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="nat-geo wild" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/chaine-nat-geo-wild.png", nat-geo wild
https://opus.cf/allfrtvstrm/tkn/bbb/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/nat_geo_wild/nat_geo_wild.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="nat-geo" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/chaine-national-geographic.png", nat-geo
https://opus.re/allfrtvstrm/tkn/sap2/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/index.m3u8?id=10
#EXTINF:-1 group-title="FRANCE" tvg-id="serie club" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/serieclub.jpg", serie club
https://opus.cf/allfrtvstrm/tkn/bbb/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/serie_club/serie_club.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="Dix" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/10-green.png", Dix
https://opus.re/allfrtvstrm/tkn/ca/dixeco/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/chunklist.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="Action" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/action.JPG", Action
https://opus.re/allfrtvstrm/tkn/abwebtk/index.php/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/live.actiontv.fr/actiontv.isml/manifest.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="Cine Polar" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/polar.png", Cine Polar
https://opus.re/allfrtvstrm/tkn/btv/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/mcm.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="Cine FX" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/cinefx.png", Cine FX
https://opus.re/allfrtvstrm/tkn/btv/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/histoire.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="TCM CINEMA" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/tcm-cinema.jpg", TCM CINEMA
https://opus.re/allfrtvstrm/tkn/newcrab/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/index.m3u8?id=1654
#EXTINF:-1 group-title="FRANCE" tvg-id="Ciné + Classic" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/CINE+CLASSIC.JPG", Ciné + Classic
https://opus.re/allfrtvstrm/tkn/newcrab/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/index.m3u8?id=449
#EXTINF:-1 group-title="FRANCE" tvg-id="Ciné + Premier" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/CINE+PREMIER.JPG", Ciné + Premier
https://opus.re/allfrtvstrm/tkn/newcrab/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/index.m3u8?id=445
#EXTINF:-1 group-title="FRANCE" tvg-id="cine plus frisson" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/cine+frisson.png", cine plus frisson
https://opus.cf/allfrtvstrm/tkn/bbb/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/cine_plus_frisson/cine_plus_frisson.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="cine plus emotion" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/cine+emotion.png", cine plus emotion
https://opus.cf/allfrtvstrm/tkn/bbb/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/cine_plus_emotion/cine_plus_emotion.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="cine plus famiz" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/cine+famiz.png", cine plus famiz
https://opus.cf/allfrtvstrm/tkn/bbb/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/cine_plus_famiz/cine_plus_famiz.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="cine plus club" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/cine+club", cine plus club
https://opus.cf/allfrtvstrm/tkn/bbb/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/cine_plus_club/cine_plus_club.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="paramount-channel" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/paramount-channel.png", paramount-channel
https://opus.re/allfrtvstrm/tkn/newcrab/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/index.m3u8?id=418
#EXTINF:-1 group-title="FRANCE" tvg-id="OCS MAX" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/chaine-ocs-max.png", OCS MAX
https://opus.cf/allfrtvstrm/tkn/bbb/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/ocs_max/ocs_max.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="OCS CITY" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/chaine-ocs-city.png", OCS CITY
https://opus.cf/allfrtvstrm/tkn/bbb/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/ocs_novo/ocs_novo.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="OCS CHOC" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/chaine-ocs-choc.png", OCS CHOC
https://opus.cf/allfrtvstrm/tkn/bbb/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/ocs_choc/ocs_choc.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="OCS GEANTS" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/ocs-geants.png", OCS GEANTS
https://opus.cf/allfrtvstrm/tkn/bbb/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/ocs_geants/ocs_geants.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="RMC Decouverte" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/rmc-d.jpg", RMC Decouverte
https://opus.re/allfrtvstrm/tkn/wild/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2059/17.m3u8?fuseau=5400
#EXTINF:-1 group-title="FRANCE" tvg-id="Rouge tv" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/rougetv.jpg", Rouge tv
https://opus.re/allfrtvstrm/tkn/wild/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2047/master.m3u8?fuseau=5400
#EXTINF:-1 group-title="FRANCE" tvg-id="TF1" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/tf1.jpg", TF1
https://opus.re/allfrtvstrm/tkn/wild/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2027/17.m3u8?fuseau=5400
#EXTINF:-1 group-title="FRANCE" tvg-id="France 2" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/chaine-france-2.png", France 2
https://opus.re/allfrtvstrm/tkn/wild/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2028/17.m3u8?fuseau=5400
#EXTINF:-1 group-title="FRANCE" tvg-id="France 3" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/chaine-france-3.png", France 3
https://opus.re/allfrtvstrm/tkn/wild/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2008/17.m3u8?fuseau=5400
#EXTINF:-1 group-title="FRANCE" tvg-id="France 4" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/chaine-france-4.png", France 4
https://opus.re/allfrtvstrm/tkn/wild/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2009/17.m3u8?fuseau=5400
#EXTINF:-1 group-title="FRANCE" tvg-id="France 5" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/chaine-france-5.png", France 5
https://opus.re/allfrtvstrm/tkn/wild/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2010/17.m3u8?fuseau=5400
#EXTINF:-1 group-title="FRANCE" tvg-id="France O" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/chaine-france-o.png", France O
https://opus.re/allfrtvstrm/tkn/wild/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2015/17.m3u8?fuseau=5400
#EXTINF:-1 group-title="FRANCE" tvg-id="M6" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/m6.gif", M6
https://opus.re/allfrtvstrm/tkn/wild/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2026/17.m3u8?fuseau=5400
#EXTINF:-1 group-title="FRANCE" tvg-id="6ter" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/6ter.png", 6ter
https://opus.re/allfrtvstrm/tkn/wild/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2057/17.m3u8?fuseau=5400
#EXTINF:-1 group-title="FRANCE" tvg-id="W9" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/w9.png", W9
https://opus.re/allfrtvstrm/tkn/wild/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2022/17.m3u8?fuseau=5400
#EXTINF:-1 group-title="FRANCE" tvg-id="D8" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/C8.jpg", D8
https://opus.re/allfrtvstrm/tkn/wild/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2018/17.m3u8?fuseau=5400
#EXTINF:-1 group-title="FRANCE" tvg-id="numero 23" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/23.png", numero 23
https://opus.re/allfrtvstrm/tkn/wild/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2062/17.m3u8?fuseau=5400
#EXTINF:-1 group-title="FRANCE" tvg-id="cherie 25" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/25.png", cherie 25
https://opus.re/allfrtvstrm/tkn/wild/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2060/17.m3u8?fuseau=5400
#EXTINF:-1 group-title="FRANCE" tvg-id="nrj 12" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/nrj12.png", nrj 12
https://opus.re/allfrtvstrm/tkn/wild/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2017/17.m3u8?fuseau=5400
#EXTINF:-1 group-title="FRANCE" tvg-id="TMC" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/tmc.gif", TMC
https://opus.re/allfrtvstrm/tkn/wild/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2023/17.m3u8?fuseau=5400
#EXTINF:-1 group-title="FRANCE" tvg-id="chaine-tfx" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/chaine-tfx.png", chaine-tfx
https://opus.re/allfrtvstrm/tkn/wild/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2012/17.m3u8?fuseau=5400
#EXTINF:-1 group-title="FRANCE" tvg-id="chaine-tf1-series-films" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/tf1-series-films-min.jpg", chaine-tf1-series-films
https://opus.re/allfrtvstrm/tkn/wild/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2061/17.m3u8?fuseau=5400
#EXTINF:-1 group-title="FRANCE" tvg-id="rts un" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/rtsun.jpg", rts un
https://opus.re/allfrtvstrm/tkn/wild/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2034/17.m3u8?fuseau=5400
#EXTINF:-1 group-title="FRANCE" tvg-id="rts deux" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/rtsdeux.jpg", rts deux
https://opus.re/allfrtvstrm/tkn/wild/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2035/17.m3u8?fuseau=5400
#EXTINF:-1 group-title="FRANCE" tvg-id="RTL9" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/rtl-9.png", RTL9
https://opus.re/allfrtvstrm/tkn/wild/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2014/17.m3u8?fuseau=5400
#EXTINF:-1 group-title="FRANCE" tvg-id="Rouge tv" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/rougetv.jpg", Rouge tv
https://opus.re/allfrtvstrm/tkn/wild/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/2047/17.m3u8?fuseau=5400
#EXTINF:-1 group-title="FRANCE" tvg-id="GOLF CHANNEL" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/golf.png", GOLF CHANNEL
https://opus.re/allfrtvstrm/tkn/abwebtk/index.php/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/live.golfchannel.fr/golfchannel.isml/manifest.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="Lucky Jack" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/luckyjack.jpg", Lucky Jack
https://opus.re/allfrtvstrm/tkn/abwebtk/index.php/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/luckyjack.akamaized.net/luckyjack.isml/manifest.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="CCTV-F" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/logo_cctv.jpg", CCTV-F
https://opus.re/tkn/s0/ab2fe38e096bbe0a202bd7d7794e366eba5406ea/cctv-f.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="Manitoba" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/src.png", Manitoba
https://opus.re/allfrtvstrm/tkn/cans/ab2fe38e096bbe0a202bd7d7794e366eba5406ea/https://srclive-lh.akamaihd.net/i/cancbwft_1@192900/master.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="Vancouver" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/src.png", Vancouver
https://opus.re/allfrtvstrm/tkn/cans/ab2fe38e096bbe0a202bd7d7794e366eba5406ea/https://srclive-lh.akamaihd.net/i/cancbuft_1@192906/master.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="RTBF LA UNE" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/laune.png", RTBF LA UNE
https://opus.re/c8/ab2fe38e096bbe0a202bd7d7794e366eba5406ea/laune-audio_1=128000-video=2000000.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="RTBF LA DEUX" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/ladeux.png", RTBF LA DEUX
https://opus.re/c8/ab2fe38e096bbe0a202bd7d7794e366eba5406ea/ladeux-audio_1=128000-video=2000000.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="RTBF LA TROIS" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/latrois.png", RTBF LA TROIS
https://opus.re/c8/ab2fe38e096bbe0a202bd7d7794e366eba5406ea/latrois-audio_1=128000-video=2000000.m3u8
#EXTINF:-1 group-title="FRANCE" tvg-id="Canal +" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/canalplus.jpg", Canal +
https://opus.re/allfrtvstrm/tkn/newcrab/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/index.m3u8?id=406
#EXTINF:-1 group-title="FRANCE" tvg-id="Canal +" tvg-logo="https://opus.re/img-p/3137cb6c3a1e85eafe70354a743f3960/img/canalplus.jpg", Canal +
https://opus.re/allfrtvstrm/tkn/sap2/ZGHmAwHjAGH4AP0kAGZ2AGD4Zmt0YGt5AwZ4ZQSvMJV5MTDlBTWwMwp1ATR3Z2Z0L2AwLGqxYGL2LGOxZQD1ZGp3BJLmZwSyZGZ5AmR5ZQOuMQDkL2Lj/index.m3u8?id=1933
#EXTINF:-1 group-title="FILMS QUEBEC" tvg-id="" tvg-logo="https://quebeccinema.ca/img/layout/logo.png",Le déclin de l'empire américain
http://46.166.142.196:1935/debrideur/_definst_/debrid_script/smil:aHR0cDovL3VwdG9ib3guY29tL213YTI4b2lmZXQ3YQ==-0218.smil/chunklist_w1843045551_b3510633_t64IEhEIFF1YWxpdHkg.m3u8

#EXTINF:-1 group-title="FILMS QUEBEC" tvg-id="" tvg-logo="https://quebeccinema.ca/img/layout/logo.png", Les invasions barbares
http://46.166.142.96:1935/debrideur/_definst_/debrid_script/smil:aHR0cHM6Ly95Z2d0b3JyZW50LmNvbS9lbmdpbmUvZG93bmxvYWRfdG9ycmVudD9pZD0zNDgzOXo=-0218.smil/chunklist_w1455915517_b3644100_t64IEhEIFF1YWxpdHkg.m3u8

#EXTINF:-1 group-title="FILMS QUEBEC" tvg-id="" tvg-logo="https://quebeccinema.ca/img/layout/logo.png", Le règne de la beauté
http://46.166.139.28/mp4/aHR0cHM6Ly8xZmljaGllci5jb20vP2p2Zm1kOG94a2g=.mp4

#EXTINF:-1 group-title="FILMS QUEBEC" tvg-id="" tvg-logo="https://quebeccinema.ca/img/layout/logo.png", Gerry
http://46.166.139.28/mp4/aHR0cDovL3d3dy50NDExLmFsL3RvcnJlbnRzL2Rvd25sb2FkLz9pZD01MTkxNTg4.mp4

#EXTINF:-1 group-title="FILMS QUEBEC" tvg-id="" tvg-logo="https://quebeccinema.ca/img/layout/logo.png",Maurice Richard
http://46.166.142.83:1935/debrideur/_definst_/debrid_script/smil:aHR0cDovL3d3dy50NDExLmFpL3RvcnJlbnRzL2Rvd25sb2FkLz9pZD01MDA2MzY3-0218.smil/chunklist_w620859733_b3644100_t64IEhEIFF1YWxpdHkg.m3u8

#EXTINF:-1 group-title="FILMS QUEBEC" tvg-id="" tvg-logo="https://quebeccinema.ca/img/layout/logo.png",La Florida
http://46.166.142.196/mp4/aHR0cHM6Ly93dzIueWdndG9ycmVudC5pcy9lbmdpbmUvZG93bmxvYWRfdG9ycmVudD9pZD0xOTg3MjE=.mp4

#EXTINF:-1 group-title="FILMS QUEBEC" tvg-id="" tvg-logo="https://quebeccinema.ca/img/layout/logo.png",Les Boys
http://46.166.142.200:1935/debrideur/_definst_/debrid_script/smil:aHR0cDovL3d3dy50NDExLmxpL3RvcnJlbnRzL2Rvd25sb2FkLz9pZD01MDM1Mjg4-0218.smil/chunklist_w2027295703_b4707214_t64IEhEIFF1YWxpdHkg.m3u8

#EXTINF:-1 group-title="FILMS QUEBEC" tvg-id="" tvg-logo="https://quebeccinema.ca/img/layout/logo.png",la forteresse suspendue
http://46.166.142.200/mp4/aHR0cDovL3d3dy50NDExLmFsL3RvcnJlbnRzL2Rvd25sb2FkLz9pZD0xMDIwMDY=.mp4

#EXTINF:-1 group-title="FILMS QUEBEC" tvg-id="" tvg-logo="https://quebeccinema.ca/img/layout/logo.png",Tom a la ferme
http://46.166.142.95:1935/debrideur/_definst_/debrid_script/smil:aHR0cHM6Ly8xZmljaGllci5jb20vP3A3ajB0Z2p2MWI=-0218.smil/chunklist_w730713147_b2016995_t64IEhEIFF1YWxpdHkg.m3u8

#EXTINF:-1 group-title="FILMS QUEBEC" tvg-id="" tvg-logo="https://quebeccinema.ca/img/layout/logo.png",J'ai tué ma mère
http://46.166.139.28/mp4/aHR0cDovL3cyZ2M2NS4xZmljaGllci5jb20v.mp4

#EXTINF:-1 group-title="FILMS QUEBEC" tvg-id="" tvg-logo="https://quebeccinema.ca/img/layout/logo.png",Mommy
https://1fhjlow.oloadcdn.net/dl/l/hSZcTkMbfmmGjqFN/wnbypDKBYl4/%29-%3DMommy+%282014%29+%5B1080p%5D+FRENCH+BluRay+x264-PopHD.m.mp4?mime=true

#EXTINF:-1 group-title="FILMS QUEBEC" tvg-id="" tvg-logo="https://quebeccinema.ca/img/layout/logo.png",Laurence Anyways
https://www65.uptostream.com/l4604df57a/360/0/video.mp4

#EXTINF:1,Les amours imaginaires
http://46.166.142.92:1935/debrideur/_definst_/debrid_script/smil:aHR0cDovL3d3dy50NDExLmxpL3RvcnJlbnRzL2Rvd25sb2FkLz9pZD01MDk1MDI1-0218.smil/chunklist_w1676602447_b3451885_t64IEhEIFF1YWxpdHkg.m3u8

#EXTINF:-1 group-title="FILMS QUEBEC" tvg-id="" tvg-logo="https://quebeccinema.ca/img/layout/logo.png",5150 rue des ormes
http://46.166.142.96/mp4/aHR0cDovL3VwdG9ib3guY29tL244ZmtudmhocXlkOQ==.mp4

#EXTINF:-1 group-title="FILMS QUEBEC" tvg-id="" tvg-logo="https://quebeccinema.ca/img/layout/logo.png", Les sept jours du talion
http://46.166.142.95:1935/debrideur/_definst_/debrid_script/smil:aHR0cDovL3d3dy50NDExLmxpL3RvcnJlbnRzL2Rvd25sb2FkLz9pZD01MzMxNjQ5-0218.smil/chunklist_w856831588_b3781148_t64IEhEIFF1YWxpdHkg.m3u8

#EXTINF:-1 group-title="FILMS QUEBEC" tvg-id="" tvg-logo="https://quebeccinema.ca/img/layout/logo.png",L'impasse du désir
http://46.166.142.92/mp4/aHR0cDovL3JpeTFmbS4xZmljaGllci5jb20v.mp4

#EXTINF:-1 group-title="FILMS QUEBEC" tvg-id="" tvg-logo="https://quebeccinema.ca/img/layout/logo.png", l'âge des ténèbres
http://46.166.142.92/mp4/aHR0cHM6Ly93dzQueWdndG9ycmVudC5pcy9lbmdpbmUvZG93bmxvYWRfdG9ycmVudD9pZD0yMTE3NDQ=.mp4

#EXTINF:-1 group-title="FILMS QUEBEC" tvg-id="" tvg-logo="https://quebeccinema.ca/img/layout/logo.png",Léolo
http://46.166.139.28:1935/debrideur/_definst_/debrid_script/smil:aHR0cDovL3d3dy50NDExLmxpL3RvcnJlbnRzL2Rvd25sb2FkLz9pZD01Mzc3ODk1-0218.smil/chunklist_w1869963291_b3284100_t64IEhEIFF1YWxpdHkg.m3u8

#EXTINF:-1 group-title="FILMS QUEBEC" tvg-id="" tvg-logo="https://quebeccinema.ca/img/layout/logo.png",Jésus de Montréal
http://46.166.139.28/mp4/aHR0cDovL3d3dy50NDExLmxpL3RvcnJlbnRzL2Rvd25sb2FkLz9pZD01NjQwODk5.mp4

#EXTINF:-1 group-title="FILMS QUEBEC" tvg-id="" tvg-logo="https://quebeccinema.ca/img/layout/logo.png",Les affamés
https://real-debrid.com/streaming-Y3DDYC2QNTE4M34
